### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by viktor1970** [psychogenic/Chronos#2]
Hallo, I installed both Time and Chronos libs, but when I try to compile an example I always get a lot of errors. Lib path is correct

Arduino:1.8.1 (Windows 10), Scheda:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from C:\Users\vitto\OneDrive\circuiti\libraries\Chronos\src/chronosinc/../chronosinc/platform/timesource.h:36:0,

                 from C:\Users\vitto\OneDrive\circuiti\libraries\Chronos\src/chronosinc/DateTime.h:38,

                 from C:\Users\vitto\OneDrive\circuiti\libraries\Chronos\src/Chronos.h:79,

                 from C:\Users\vitto\AppData\Local\Temp\arduino_modified_sketch_717444\DateTime.ino:45:

C:\Users\vitto\OneDrive\circuiti\libraries\Chronos\src/chronosinc/DateTime.h: In member function 'void Chronos::DateTime::initElements() const':

C:\Users\vitto\OneDrive\circuiti\libraries\Chronos\src/chronosinc/../chronosinc/platform/../../chronosinc/platform/timesourceTimelib.h:39:29: error: invalid initialization of reference of type 'tmElements_t&' from expression of type 'Chronos::TimeElements'

  ::breakTime(epoch, elements);

                             ^

C:\Users\vitto\OneDrive\circuiti\libraries\Chronos\src/chronosinc/DateTime.h:380:78: note: in expansion of macro 'DATETIME_CONVERT_EPOCH_INTO_TIMELEMENTS'

  void initElements() const {if (_elements.Year || _elements.Month) {return;} DATETIME_CONVERT_EPOCH_INTO_TIMELEMENTS(epoch, _elements); }

                                                                      ^

In file included from C:\Users\vitto\AppData\Local\Temp\arduino_modified_sketch_717444\DateTime.ino:44:0:

C:\Users\vitto\OneDrive\circuiti\libraries\Time/TimeLib.h:138:6: note: in passing argument 2 of 'void breakTime(time_t, tmElements_t&)'

 void breakTime(time_t time, tmElements_t &tm);  // break time_t into elements

      ^

**Comment by psychogenic** [comment]
Hi... closed before I got a chance to check.

Was this resolved?  What was the issue?

Thanks!

**Comment by viktor1970** [comment]
Hallo, sorry I was too fast :)
I experienced issue including Time.h: I've to include TimeLib.h for getting work (otherwise compiler reports "tmElements_t does not name a type", I don't know why).

I tried to compile for a NodeMCU, same error. I modified line 43 of timeExtInc.h to #include <TimeLib.h> and it works fine.

Regards,

Vikt

**Comment by psychogenic** [comment]
oh, ok... well that counts as a bug.  I'll try it out and update accordingly, asap.

Thanks,
P

**Comment by alljoynsville** [comment]
hi, plz add the line to src/chronosinc/timeExtInc.h

#include <TimeLib.h>

for me it solved the problem

**Comment by Daniel-Ebert** [comment]
Same problem around here, thanks for providing the solution!
The library does not compile at all without that....

> 
> 
> hi, plz add the line to src/chronosinc/timeExtInc.h
> 
> #include <TimeLib.h>
> 
> for me it solved the problem

**Comment by hlovdal** [comment]
Duplicate of #5.
